security:
    encoders:
        App\Entity\User: bcrypt    
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: our_db_provider            
            form_login:
                login_path: login
                check_path: login            