#index:
#    path: /
#    controller: App\Controller\DefaultController::index

genres:
    path: /genres
    controller: App\Controller\GenresController::index
    
genre_edit:
    path: /genre_edit/{id}
    controller: App\Controller\GenresController::edit
    
genre_delete:  
    path: /genre_delete/{id}
    controller: App\Controller\GenresController::delete 
    
login:
    path: /login
    controller: App\Controller\SecurityController::login
    
index:
    path: /
    controller: App\Controller\IndexController::index  
    
authors:
    path: /authors
    controller: App\Controller\AuthorsController::index    
    
author_edit:
    path: /author_edit/{id}
    controller: App\Controller\AuthorsController::edit 
    
author_delete:  
    path: /author_delete/{id}
    controller: App\Controller\AuthorsController::delete     