genres:
    path: /genres/{id}
    controller: App\Controller\GenresController::index
    defaults:   { id: 0 }
    
genre_edit:
    path: /genre_edit/{id}
    controller: App\Controller\GenresController::edit
    
genre_delete:  
    path: /genre_delete/{id}
    controller: App\Controller\GenresController::delete 
    
user_registration:
    path: /register
    controller: App\Controller\RegistrationController::register 
    
login:
    path: /login
    controller: App\Controller\SecurityController::login    
    
index:
    path: /
    controller: App\Controller\IndexController::index  
    
authors:
    path: /authors/{id}
    controller: App\Controller\AuthorsController::index  
    defaults:   { id: 0 }    
    
author_edit:
    path: /author_edit/{id}
    controller: App\Controller\AuthorsController::edit 
    
author_delete:  
    path: /author_delete/{id}
    controller: App\Controller\AuthorsController::delete
    
book:  
    path: /book/{id}
    controller: App\Controller\BooksController::book    
    
book_edit:
    path: /book_edit/{id}
    controller: App\Controller\BooksController::edit 
    
book_delete:  
    path: /book_delete/{id}
    controller: App\Controller\BooksController::delete 
    
user_profile:
    path: /user/{id}
    controller: App\Controller\UserController::profile 

addbooktofavorites:    
    path: /addbooktofavorites
    controller: App\Controller\UserController::addBookToFavorites 

removebookfromfavorites:    
    path: /removebookfromfavorites
    controller: App\Controller\UserController::removeBookFromFavorites     